In [40]:
import pandas as pd
import numpy as np

# Data Frame

In [41]:
data = {
    "Names": ["Akash", "Rahul", "Priya", "Neha","Akash"],
    "Ages": [25, 30, 27, np.nan,25],
    "Departments": ["IT", "HR", "Finance", "Marketing","IT"],
    "Salaries": [60000, 50000, 55000, 52000,60000]
}

print(data)

{'Names': ['Akash', 'Rahul', 'Priya', 'Neha', 'Akash'], 'Ages': [25, 30, 27, nan, 25], 'Departments': ['IT', 'HR', 'Finance', 'Marketing', 'IT'], 'Salaries': [60000, 50000, 55000, 52000, 60000]}

In [42]:
df = pd.DataFrame(data)
df

   Names  Ages Departments  Salaries
0  Akash  25.0          IT     60000
1  Rahul  30.0          HR     50000
2  Priya  27.0     Finance     55000
3   Neha   NaN   Marketing     52000
4  Akash  25.0          IT     60000

In [43]:
df.head(2)

   Names  Ages Departments  Salaries
0  Akash  25.0          IT     60000
1  Rahul  30.0          HR     50000

In [44]:
df.tail(2)

   Names  Ages Departments  Salaries
3   Neha   NaN   Marketing     52000
4  Akash  25.0          IT     60000

In [45]:
#loc and #iloc
df.loc[1:2]

   Names  Ages Departments  Salaries
1  Rahul  30.0          HR     50000
2  Priya  27.0     Finance     55000

In [46]:
df.iloc[1:2 ]

   Names  Ages Departments  Salaries
1  Rahul  30.0          HR     50000

In [47]:
df.loc[1:3,["Ages","Departments"]]  #row and col

   Ages Departments
1  30.0          HR
2  27.0     Finance
3   NaN   Marketing

In [48]:
df["Ages"] #for single col

0    25.0
1    30.0
2    27.0
3     NaN
4    25.0
Name: Ages, dtype: float64

In [49]:
#for multiple col
df[["Ages","Salaries"]]

   Ages  Salaries
0  25.0     60000
1  30.0     50000
2  27.0     55000
3   NaN     52000
4  25.0     60000

In [50]:
df.drop("Ages",axis=1) #delete and return new dataframe

   Names Departments  Salaries
0  Akash          IT     60000
1  Rahul          HR     50000
2  Priya     Finance     55000
3   Neha   Marketing     52000
4  Akash          IT     60000

In [51]:
df #actual dataframe still exist with all columns

   Names  Ages Departments  Salaries
0  Akash  25.0          IT     60000
1  Rahul  30.0          HR     50000
2  Priya  27.0     Finance     55000
3   Neha   NaN   Marketing     52000
4  Akash  25.0          IT     60000

In [52]:
df.shape

(5, 4)

In [53]:
df.dtypes

Names           object
Ages           float64
Departments     object
Salaries         int64
dtype: object

In [54]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Names        5 non-null      object
 1   Ages         4 non-null      float64
 2   Departments  5 non-null      object
 3   Salaries     5 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 292.0+ bytes

In [55]:
df.describe()

            Ages    Salaries
count   4.000000      5.0000
mean   26.750000  55400.0000
std     2.362908   4560.7017
min    25.000000  50000.0000
25%    25.000000  52000.0000
50%    26.000000  55000.0000
75%    27.750000  60000.0000
max    30.000000  60000.0000

In [56]:
df["Salaries"]

0    60000
1    50000
2    55000
3    52000
4    60000
Name: Salaries, dtype: int64

In [57]:
#BroadCasting  #increase salaries by 5000
df["Salaries"]+5000

0    65000
1    55000
2    60000
3    57000
4    65000
Name: Salaries, dtype: int64

In [58]:
#Renaming columns
df.rename(columns = {"Departments":"Dept"})

   Names  Ages       Dept  Salaries
0  Akash  25.0         IT     60000
1  Rahul  30.0         HR     50000
2  Priya  27.0    Finance     55000
3   Neha   NaN  Marketing     52000
4  Akash  25.0         IT     60000

In [59]:
df #actual dataframe is not chnage if i want to chmage it use inplace=True

   Names  Ages Departments  Salaries
0  Akash  25.0          IT     60000
1  Rahul  30.0          HR     50000
2  Priya  27.0     Finance     55000
3   Neha   NaN   Marketing     52000
4  Akash  25.0          IT     60000

In [60]:
df.rename(columns = {"Departments":"Dept"},inplace=True)

In [61]:
df

   Names  Ages       Dept  Salaries
0  Akash  25.0         IT     60000
1  Rahul  30.0         HR     50000
2  Priya  27.0    Finance     55000
3   Neha   NaN  Marketing     52000
4  Akash  25.0         IT     60000

In [62]:
df["Salaries"].unique()

array([60000, 50000, 55000, 52000])

In [63]:
df["Dept"].value_counts()

Dept
IT           2
HR           1
Finance      1
Marketing    1
Name: count, dtype: int64

In [64]:
#create new col
df["Promoted Employees"] = df["Salaries"]+10000

In [65]:
df

   Names  Ages       Dept  Salaries  Promoted Employees
0  Akash  25.0         IT     60000               70000
1  Rahul  30.0         HR     50000               60000
2  Priya  27.0    Finance     55000               65000
3   Neha   NaN  Marketing     52000               62000
4  Akash  25.0         IT     60000               70000

# Data Cleaning

In [66]:
df.isnull().sum()

Names                 0
Ages                  1
Dept                  0
Salaries              0
Promoted Employees    0
dtype: int64

In [67]:
df

   Names  Ages       Dept  Salaries  Promoted Employees
0  Akash  25.0         IT     60000               70000
1  Rahul  30.0         HR     50000               60000
2  Priya  27.0    Finance     55000               65000
3   Neha   NaN  Marketing     52000               62000
4  Akash  25.0         IT     60000               70000

In [68]:
df.dropna(how = "any") # if any value in any row found then remove
# df.dropna(how = "all") # if all values are null in any row then remove

   Names  Ages     Dept  Salaries  Promoted Employees
0  Akash  25.0       IT     60000               70000
1  Rahul  30.0       HR     50000               60000
2  Priya  27.0  Finance     55000               65000
4  Akash  25.0       IT     60000               70000

In [69]:
#Fill missing values
df["Ages"].fillna(df["Ages"].mean()) #Mean
# df["Ages"].fillna(df["Ages"].median()) #Media
# df["Ages"].fillna(df["Ages"].mode()) #Mode

0    25.00
1    30.00
2    27.00
3    26.75
4    25.00
Name: Ages, dtype: float64

In [70]:
df["Ages"].fillna(method = "ffill")  #ForwardFill

C:\Users\91790\AppData\Local\Temp\ipykernel_22692\1228638201.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Ages"].fillna(method = "ffill")  #ForwardFill

0    25.0
1    30.0
2    27.0
3    27.0
4    25.0
Name: Ages, dtype: float64

In [71]:
df["Ages"].fillna(method = "bfill")  #BackwardFill
#still NaN beacuse there is not value after that nan value so it stay NaN

C:\Users\91790\AppData\Local\Temp\ipykernel_22692\4000896767.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df["Ages"].fillna(method = "bfill")  #BackwardFill

0    25.0
1    30.0
2    27.0
3    25.0
4    25.0
Name: Ages, dtype: float64

In [72]:
df["Name"] = df["Names"].replace("Priya","Riya")
df

   Names  Ages       Dept  Salaries  Promoted Employees   Name
0  Akash  25.0         IT     60000               70000  Akash
1  Rahul  30.0         HR     50000               60000  Rahul
2  Priya  27.0    Finance     55000               65000   Riya
3   Neha   NaN  Marketing     52000               62000   Neha
4  Akash  25.0         IT     60000               70000  Akash

In [73]:
#Duplicate Values
df.duplicated(keep ="first")

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [74]:
df = df.drop_duplicates()
df

   Names  Ages       Dept  Salaries  Promoted Employees   Name
0  Akash  25.0         IT     60000               70000  Akash
1  Rahul  30.0         HR     50000               60000  Rahul
2  Priya  27.0    Finance     55000               65000   Riya
3   Neha   NaN  Marketing     52000               62000   Neha

In [75]:
#Invalid values
#lambda
df["Promoted Employees"] = df["Promoted Employees"].apply(lambda x : x/10 if x>55000 else x)
df

C:\Users\91790\AppData\Local\Temp\ipykernel_22692\3379547369.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Promoted Employees"] = df["Promoted Employees"].apply(lambda x : x/10 if x>55000 else x)

   Names  Ages       Dept  Salaries  Promoted Employees   Name
0  Akash  25.0         IT     60000              7000.0  Akash
1  Rahul  30.0         HR     50000              6000.0  Rahul
2  Priya  27.0    Finance     55000              6500.0   Riya
3   Neha   NaN  Marketing     52000              6200.0   Neha

In [ ]:
# #String functions
# #inCase (Demo)
# name = "Raj_bahadur"
# df[["First_name","Last_name"]] = df["name"].str.split("_")
# df

In [ ]:
#apply nad lambda
def multiplay_age(x):
    return x*2
df["Ages" ]= df["Ages"].apply(multiplay_age)
df

   Names  Ages       Dept  Salaries  Promoted Employees   Name
0  Akash  50.0         IT     60000              7000.0  Akash
1  Rahul  60.0         HR     50000              6000.0  Rahul
2  Priya  54.0    Finance     55000              6500.0   Riya
3   Neha   NaN  Marketing     52000              6200.0   Neha

In [ ]:
df["Ages"] = df["Ages"].apply(lambda x: x/2)
df

   Names  Ages       Dept  Salaries  Promoted Employees   Name
0  Akash  25.0         IT     60000              7000.0  Akash
1  Rahul  30.0         HR     50000              6000.0  Rahul
2  Priya  27.0    Finance     55000              6500.0   Riya
3   Neha   NaN  Marketing     52000              6200.0   Neha

In [90]:
#Joins And Merges
department_info = {
    "Dept":["IT","HR","Finance"],
    "Location":["New York","San Francisco","Chicago"],
    "Manager":["Laura","Steve","Nina"]         
}

In [91]:
df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       IT       New York   Laura
1       HR  San Francisco   Steve
2  Finance        Chicago    Nina

In [92]:
#concat
pd.concat([df,df2])

,Names,Ages,Dept,Salaries,Promoted Employees,Name,Location,Manager
0,Akash,25.0,IT,60000.0,7000.0,Akash,NaN,NaN
1,Rahul,30.0,HR,50000.0,6000.0,Rahul,NaN,NaN
2,Priya,27.0,Finance,55000.0,6500.0,Riya,NaN,NaN
3,Neha,NaN,Marketing,52000.0,6200.0,Neha,NaN,NaN
0,NaN,NaN,IT,NaN,NaN,NaN,New York,Laura
1,NaN,NaN,HR,NaN,NaN,NaN,San Francisco,Steve
2,NaN,NaN,Finance,NaN,NaN,NaN,Chicago,Nina

In [93]:
#concat
pd.concat([df,df2],axis=1)

,Names,Ages,Dept,Salaries,Promoted Employees,Name,Dept,Location,Manager
0,Akash,25.0,IT,60000,7000.0,Akash,IT,New York,Laura
1,Rahul,30.0,HR,50000,6000.0,Rahul,HR,San Francisco,Steve
2,Priya,27.0,Finance,55000,6500.0,Riya,Finance,Chicago,Nina
3,Neha,NaN,Marketing,52000,6200.0,Neha,NaN,NaN,NaN

In [ ]:
#Merge
pd.merge(df, df2, on = "Dept")

,Names,Ages,Dept,Salaries,Promoted Employees,Name,Location,Manager
0,Akash,25.0,IT,60000,7000.0,Akash,New York,Laura
1,Rahul,30.0,HR,50000,6000.0,Rahul,San Francisco,Steve
2,Priya,27.0,Finance,55000,6500.0,Riya,Chicago,Nina

In [ ]:
#How to read csv file
data = pd.read_csv("PATH or NAME")